### ISSUE TITLE
The URL link in the `Contributing to these docs` section is broken.

### ISSUE THREAD

**Issue by cr-ishikawa** [komapper/komapper-docs#25]
https://github.com/komapper/komapper-docs#contributing-to-these-docs

Please correct broken links.

**Comment by nakamura-to** [comment]
We have added [CONTRIBUTING.md](https://github.com/komapper/komapper-docs/blob/ba5079753232e29cb445b2bdbde25d2ccd4005dc/CONTRIBUTING.md) instead of correcting the links.
If you have any questions, please do not hesitate to ask.

**Comment by cr-ishikawa** [comment]
@nakamura-to 
Thank you for your response. No problem.
